import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.css']
})
export class ContactComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

  contacts = [
    {Name: 'TVS Lamahi Motors', Address: 'lamahi , Dang', Phone: '9801106270', Email: 'sudeep.pandeya@gmail.com'},
    {Name: 'SIDDHARTHA AUTO TRADERS', Address: 'Musikot RUKUM', Phone: '9847981000', Email: 'siddharthautotraders@gmail.com'},
    {Name: 'Glory Auto Pvt. Ltd.', Address: 'RAVIBHAWAN, kathmandu', Phone: '9801091901', Email: 'receptiongloryautotvs@gmail.com'},
    {Name: 'Aman Enterprises', Address: 'Golbazar, Siraha', Phone: '9801528181', Email: 'amanenterprisestvs@gmail.com'},
    {Name: 'Jay Durga Automobiles', Address: 'Jhalari, Kanchanpur', Phone: '9848725847', Email: 'automobile.jhalari@gmail.com'},
    {Name: 'Sun Auto Sales', Address: 'Belauri, Kanchanpur', Phone: '9848425946', Email: 'sunautosales.belauri@gmail.com'},
    {Name: 'Mahamaya Trade & Suppliers', Address: 'Mahendranagar, Kanchanpur', Phone: '9858750148', Email: 'binodbhattatvs@gmail.com'},
    {Name: 'Bardiya Ras Auto & Suppliers', Address: 'Rajapur, Bardiya', Phone: '9825598527', Email: 'bardiyarus.rajapur@gmail.com'},
    {Name: 'Top Rides Autohub Pvt.Ltd', Address: 'Tikapur, Kailali', Phone: '9858060023', Email: 'tvstikapur@gmail.com'},
    {Name: 'B & A Automotives', Address: 'Attariya, Kailali', Phone: '9858420820', Email: 'tvsattariya76@gmail.com'},
    {Name: 'Namuna Auto Parts & Suppliers', Address: 'Dadeladhura', Phone: '9858751212', Email: 'amarbdpun@gmail.com'},
    {Name: 'Ram Automobiles', Address: 'Bansgadhi, Bardiya', Phone: '9816504767', Email: 'Ranautomubailes79@gmail.com'},
    {Name: 'Grace & Global Trading Pvt.Ltd', Address: 'Nepalgunj -2, Banke', Phone: '9858025019', Email: 'graceglobaltradingpvtltd@gmail.com'},
    {Name: 'Mama Bhanja Auto Motors Parts', Address: 'Jumla', Phone: '9848073491', Email: 'abc@gmail.com'},
    {Name: 'Lila Trade House', Address: 'Pokhara, Kaski', Phone: '9858020236', Email: 'lth.gulariya@gmail.com'},
    {Name: 'Panas Automotives', Address: 'Kohalpur, Banke', Phone: '9801100861', Email: 'tvspanas2018@gmail.com'},
    {Name: 'Swargadawari Auto Distributors', Address: 'Gorahi 1, Dang', Phone: '9857830614', Email: 'swargadwariauto@gmail.com'},
    {Name: 'Sijal Automobiles', Address: 'Sainamaina, Rupandehi', Phone: '9857075807/9816', Email: 'sijalautomobiles@gmail.com'},
    {Name: 'Shree United Motors', Address: 'Argakhachi', Phone: '9857030259', Email: 'motorsunited04@gmail.com'},
    {Name: 'New sakcham Enterprise', Address: 'Lumbini parsa, kapilbastu', Phone: '9857010103', Email: 'newsakchamint8848@gmail.com'},
    {Name: 'Bina Motors', Address: 'Chandrauta, kapilbastu', Phone: '9818596637', Email: 'binamotorstvs@gmail.com'},
    {Name: 'Sunrising Business', Address: 'Manigram, Rupandehi', Phone: '9841582586', Email: 'pathakkeshab12@gmail.com'},
    {Name: 'New Modern Auto Works', Address: 'Rampur, Palpa', Phone: '9847509840', Email: 'tvsrampur777palpa@gmail.com'},
    {Name: 'Rambhadevi Auto Enterprises', Address: 'Palpa', Phone: '9867340358/ 986', Email: 'abc@gmail.com'},
    {Name: 'Om Siddhi Automobiles', Address: 'Bardaghat, Nawalparasi', Phone: '9861205377', Email: 'omsiddhiauto@gmail.com'},
    {Name: 'S.N Automobiles', Address: 'Parasi, Nawalparasi', Phone: '9857029901', Email: 'snautomobiles11@gmail.com'},
    {Name: 'Baglung Bhagawati Traders', Address: 'Baglung', Phone: '9857622446', Email: 'baglungbhagwati@yahoo.com'},
    {Name: 'Rara Automobiles', Address: 'Beni, Myagdi', Phone: '9857621863', Email: 'raraauto@gmail.com'},
    {Name: 'Bagale Traders', Address: 'Waling, Syanja', Phone: '9856055550', Email: 'bagaletraders@gmail.com'},
    {Name: 'Jivan Sahara Enterprises', Address: 'Besisahar, Lamjung', Phone: '9856045460/9840', Email: 'jeevansahara.enterprieses@gmail.com'},
    {Name: 'Khadgamai Motors', Address: 'Dumre, Tanahun', Phone: '&nbsp;9843353916', Email: 'khadgamaimotors@gmail.com'},
    {Name: 'M.S. Traders', Address: 'Damauli, Tanahun', Phone: '9819154937 / 98', Email: 'lovelydamauli@gmail.com'},
    {Name: 'Ramjali Traders', Address: 'Dulegauda, Tanahun', Phone: '9856035663', Email: 'ramjalitraders.suraj@gmail.com'},
    {Name: 'Karna Enterprises', Address: 'Gorkha', Phone: '9856043148', Email: 'karna.interprises@gmail.com'},
    {Name: 'Auto connection', Address: 'Lekhnath, Kaski', Phone: '9856044270', Email: 'abc@gmail.com'},
    {Name: 'Madhyamanchal Auto Group', Address: 'Banepa, Kavre', Phone: '9851195892', Email: 'madhyamanchalautogroup@gmail.com'},
    {Name: 'Hour Motors pvt.ltd', Address: 'Kirtipur, Kathmandu', Phone: '9851210478', Email: 'hourmotorsnp@gmail.com'},
    {Name: ' New Bike Mart Nepal Pvt. Ltd.', Address: 'Dhading', Phone: '9801050324', Email: 'abc@gmail.com'},
    {Name: 'Saanvi Auto Link', Address: 'Pepsicola, Kathmandu', Phone: '9808745740', Email: 'saanviautolink@gmail.com'},
    {Name: 'Shree Dibyashwori Auto Enterprises', Address: 'Kausaltar, Bhaktapur', Phone: '9851194855', Email: 'dibyashworienterprise@gmail.com'},
    {Name: 'Pathivara Traders', Address: 'Gwarko, Lalitpur', Phone: '9851085293', Email: 'pathivaratraders.pvt@gmail.com'},
    {Name: 'UNI Ride Auto Pvt.Ltd', Address: 'Mahalaxmisthan, Lalitpur', Phone: '9851116330', Email: 'nimenam0253@gmail.com'},
    {Name: 'K &amp; K Auto Centre', Address: 'Battishputali, Kathmandu', Phone: '9851206484', Email: 'durgabahadurkarki@yahoo.com'},
    {Name: 'Yogamber Auto', Address: 'Balaju, Kathmandu', Phone: '9851031074/9801', Email: 'dineshyogamber@gmail.com'},
    {Name: 'Auto Sound Traders', Address: 'Tusal, Kathmandu', Phone: '9851232632', Email: 'autosound2018@gmail.com'},
    {Name: 'First Choise Auto Mobiles', Address: 'Satungal, Kathmandu', Phone: '9849124781', Email: 'curfewshrestha77@gmail.com'},
    {Name: 'Bike Mart Nepal Pvt. Ltd.', Address: 'Khusibu, Kathmandu', Phone: '9841847952/ 980', Email: 'bikemartnepal@gmail.com'},
    {Name: 'Jagdamba Auto Engineering', Address: 'Sanobharyang, Kathmandu', Phone: '9802071108', Email: 'ajay.giri@jagdambamotors.com'},
    {Name: 'B & R Motors Pvt.Ltd', Address: 'Bhandara, Chitwan', Phone: '9801028399', Email: 'bhandaratvs9@gmail.com'},
    {Name: 'Madi motors', Address: 'Madi, Chitwan', Phone: '9855032307', Email: 'madimotors242@gmail.com'},
    {Name: 'Unique Auto Point', Address: 'Kawasoti, Nawalpur', Phone: '9857040674', Email: 'uniqueautoshowroom@gmail.com'},
    {Name: 'Maha Laxmi Enterprises', Address: 'Pokhara, Kaski', Phone: '9801084453', Email: 'sales.mahalaxmitandi@gmail.com'},
    {Name: 'Shah Motors', Address: 'Daldale, Chitwan', Phone: '9811197430/9855', Email: 'abc@gmail.com'},
    {Name: 'Abisha Enterprises', Address: 'Chanauli, Chitwan', Phone: '9855051761', Email: 'abishaenterprisestvs@gmail.com'},
    {Name: 'Karan Enterprises', Address: 'Kalaiya, Bara', Phone: '9855045714 / 98', Email: 'raj.pkj100@gmail.com'},
    {Name: 'D.N.K Auto Suppliers', Address: 'Palung, Makawanpur', Phone: '9809245316/9855', Email: 'draj.dhakal@gmail.com'},
    {Name: 'Sagarmatha Motors', Address: 'Jeetpur, Bara', Phone: '9818636327', Email: 'Sagarmathamotors2075@gmail.com'},
    {Name: 'Ma Ajima Traders', Address: 'Nijgadh, Bara', Phone: '9855044288', Email: 'maajimatraders@gmail.com'},
    {Name: 'Karan Enterprises', Address: 'Kalaiya, Bara', Phone: '9855045346', Email: 'karan.enterprises99@gmail.com'},
    {Name: 'Ganpati Auto &amp; Center', Address: 'Chapur, Rautahat', Phone: '9855041776', Email: 'rhpandit84@gmail.com'},
    {Name: 'Jaya Baba Bishowkarma Enterprises', Address: 'Garuda, Rautahat', Phone: '9807252449', Email: 'sandip300021@gmail.com'},
    {Name: 'Maxx Auto Pvt. Ltd.', Address: 'Birgung, Parsa', Phone: '9851056696/ 980', Email: 'maxxautopl@gmail.com'},
    {Name: 'Shrestha Traders', Address: 'Sindhuli', Phone: '9844041999', Email: 'sindhulitvs4@gmail.com'},
    {Name: 'Janaki Auto Enterprises', Address: 'Bardibas, Mahottari', Phone: '9854022307', Email: 'Janakiautobardiwas@gmail.com'},
    {Name: 'Sumit Auto enterprises', Address: 'Barthwa, Mahottari', Phone: '9854035075', Email: 'sumit.enterprises075@gmail.com'},
    {Name: 'D &amp; A Enterprises', Address: 'Lalbandi, Mahottari', Phone: '9843117969', Email: 'sushilale95@gmail.com'},
    {Name: 'Ambika Enterprises', Address: 'Loharpatti, Mahottari', Phone: '9817610915', Email: 'ambikaenterprises.jlw@gmail.com'},
    {Name: 'Ambika Enterprises', Address: 'Loharpatti, Mahottari', Phone: '9817610915', Email: 'ambikaenterprises.jlw@gmail.com'},
    {Name: 'Janani Traders', Address: 'Gausala, Mahottari', Phone: '9808438802', Email: 'sanjayshah095@gmail.com'},
    {Name: 'New Mahalaxmi Enterprises', Address: 'Ramgopalpur, Mahottari', Phone: '9814819016', Email: 'ashoknewmahalaxmi.int@gmail.com'},
    {Name: 'Janyanti Enterprises', Address: 'Dhalkebar, Dhanusha', Phone: '9804805413', Email: 'jayantienterprises.tvsdhalke@gmail.com'},
    {Name: 'Jay Hanuman Enterprises', Address: 'Sitapur, Dhanusha', Phone: '9812110264', Email: 'jayhanumanenterprises82@gmail.com'},
    {Name: 'Jay Auto Enterprises', Address: 'Dhanusha-Mahendranagar, Dhanusha', Phone: '9817827666', Email: 'jayautomobile88@gmail.com'},
    {Name: 'Aditya Auto Enterprises', Address: 'Dhanusadham, Dhanusa', Phone: '9801623444', Email: 'adityaautoenterprises@gmail.com'},
    {Name: 'S &amp; S Auto Center', Address: 'Dhanusadham -1, Dhanusa ', Phone: '9810171163', Email: 'amarjaiswalsanjani@gmail.com'},
    {Name: 'S S Auto Center', Address: 'Godar, Dhanusa', Phone: '9810171163', Email: 'ss.autocenter55@gmail.com'},
    {Name: 'Aryan Automobiles', Address: 'Janakpur, Dhanusa', Phone: '9854030441', Email: 'janakpurtvs2014@gmail.com'},
    {Name: 'Arun Enterprises', Address: 'Khadbari, Sankhuwasabha', Phone: '9852051550', Email: 'kdb.tvs@gmail.com'},
    {Name: 'BS Traders', Address: 'Surunga, Jhapa', Phone: '9851135843/9814', Email: 'bstraderstvs@gmail.com'},
    {Name: 'Shree Ganpati Traders', Address: 'Rajgadh, Jhapa', Phone: '9815955211', Email: 'tvsrajgadh@gmail.com'},
    {Name: 'Puri Brothers (Sub Dealer)', Address: 'Chandragadi, Jhapa', Phone: '9814987007', Email: 'abc@gmail.com'},
    {Name: 'NB Enterprises (Sub Dealer)', Address: 'Phidim, Paanchthar', Phone: '9841881399 / 98', Email: 'tvsphidim@gmail.com'},
    {Name: 'NB Enterprises (Sub Dealer)', Address: 'Phidim, Paanchthar', Phone: '9841881399 / 98', Email: 'tvsphidim@gmail.com'},
    {Name: 'Dg Trade', Address: 'Ilam', Phone: '9852680280', Email: 'dgtrade802@gmail.com'},
    {Name: 'Bagheshwori Automotives', Address: 'Dhanagadi, Kailali', Phone: '9804662891/091-', Email: 'bageshworiauto@gmail.com'},
    {Name: 'Bhanu Enterprises', Address: 'Surkhet', Phone: '9858055884/083-', Email: 'bhanuenterprises2073@gmail.com'},
    {Name: 'Gorkha Enterprises', Address: 'Nepalgunj -1, Banke', Phone: '9802540713/081-', Email: 'gorkhaenterprises16@gmail.com'},
    {Name: 'Om Sai Automobiles', Address: 'Nepalgunj, Banke', Phone: '9858022869/081-', Email: '09pyasi@gmail.com'},
    {Name: 'New Shrestha Enterprises', Address: 'Ghorahi, Dang', Phone: '9809703150/082-', Email: 'ss7532902@gmail.com'},
    {Name: 'H.B Auto Traders', Address: 'Tulsipur, Dang', Phone: '9857838008', Email: 'hbautotradors2020@gmail.com'},
    {Name: 'Banganga Auto Traders', Address: 'Jeetpur4, Kapilbastu', Phone: '9857031452/076-', Email: 'autobanganga@gmail.com'},
    {Name: 'Balaji Automobiles', Address: 'Bhairahawa, Rupandehi ', Phone: '9804459172/071-', Email: 'balajiautomobiles88@gmail.com'},
    {Name: 'Balaji Automobiles', Address: 'Butwal, Rupandehi', Phone: '9804459172/071-', Email: 'butwalbalaji4@gmail.com'},
    {Name: 'Laxmi Wheels PVT.LTD.', Address: 'Banepa-1, Kavre', Phone: '9801017965', Email: 'laxmiwheels.banepa@gmail.com'},
    {Name: 'R.D. Auto Group', Address: 'Sallaghari, Bhaktapur', Phone: '9851017150', Email: 'autogrouprd@gmail.com'},
    {Name: 'Jagdamba Auto Engineering', Address: 'Kupondole, Lalitpur', Phone: '9802071353/01-5', Email: 'kupondol.sales@jagdambamotors.com'},
    {Name: 'Jagdamba Auto Engineering', Address: 'Kantipath, Kathmandu', Phone: '9802071154/01-4', Email: 'sales.kantipath@jagdambamotors.com'},
    {Name: 'Jagdamba Auto Engineering', Address: 'Tinkune, Kathmandu', Phone: '9802311404', Email: 'muna_bhandari@yahoo.com'},
    {Name: 'Wonder Wheels PVT.LTD', Address: 'Maharajgunj, Kathmandu', Phone: '9843803907', Email: 'wonderwheels2020@gmail.com'},
    {Name: 'Infinity Two Wheelers Pvt. Ltd.', Address: 'Samakhusi, Kathmandu', Phone: '9851103047/9802', Email: 'infinitytwowheelers@gmail.com'},
    {Name: 'Jagdamba Auto Engineering', Address: 'Kumaripati, Lalitpur', Phone: '9802071208/01-5', Email: 'arjun.sanjel@jagdambamotors.com'},
    {Name: 'Jagdamba Auto Engineering', Address: 'Naxal, Kathmandu', Phone: '9802071202/01-4', Email: 'pampha.bhandari@jagdambamotors.com'},
    {Name: 'Jagdamba Auto Engineering', Address: 'Teku, Kathmandu', Phone: '9802071236', Email: 'sanjita.maharjan@jagdambamotors.com'},
    {Name: 'Jay Bhole Baba Engineering &amp; Sales', Address: 'Parsa, Chitwan', Phone: '9855062228/056-', Email: 'jayabhole18@gmail.com'},
    {Name: 'Malashree Motors Pvt. Ltd', Address: 'Narayanghat, Chitwan', Phone: '9801556664 / 056-572184', Email: 'sales.malashree@gmail.com'},
    {Name: 'Tara Motors Pvt Ltd', Address: 'Hetauda, Makawanpur', Phone: '9855027295/057-', Email: 'taramotors@gmail.com'},
    {Name: 'Jai Maa Durga Automobiles', Address: 'Mirchiya, Siraha', Phone: '9801605171/033-', Email: 'shiv.jaymaadurga@gmail.com'},
    {Name: ' Raj Automobiles', Address: 'Lahan, Siraha', Phone: '9805344822/033-', Email: 'rajgupta5556@gmail.com'},
    {Name: 'New Gaurav Auto Cenetr', Address: 'Biratnagar, Morang', Phone: '9852027009/021-', Email: 'gaurav.orgn@gmail.com'},
    {Name: 'New Krishna Traders', Address: 'Dharan, Sunsari', Phone: '9815330874', Email: 'newkrishnatvsdharan@gmail.com'},
    {Name: 'Paras Automobiles', Address: 'Itahari, Sunsari', Phone: '9852048056', Email: 'parasautomobiles2060@gmail.com'},
    {Name: 'Pasupati Enterprises', Address: 'Damak, Jhapa', Phone: '9844600000', Email: 'damaktvs2015@gmail.com'},
    {Name: 'Pathivara Auto Link', Address: 'Birtamode , Jhapa', Phone: '9802677189 ', Email: 'birtamodetvs@gmail.com'},
    {Name: 'Batas Borthers Pvt. Ltd.', Address: 'Pokhara, Kaski', Phone: '9856029067', Email: 'santosh@batas.com'}
  ]

}
